Np 46843 migrate all projects
BIBSYSDEV/nva-brage-migration pull request #399
Opened 2024-05-31 11:19 UTC by truhacevkir

2024-05-31 18:32 UTC, brinxmat requested changes

2024-05-31 18:32 UTC, brinxmat commented on brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/Project.java
> +        try {
A small analysis of the code and tests tells me that the following works:

```
    public static Project fromBrageValue(String value) {
        try {
            var colonIndex = value.lastIndexOf(COLON);
            var slashIndex = value.lastIndexOf(SLASH);

            var index = colonIndex > 0 ? colonIndex : slashIndex;

            return index > 0 ? extractProject(value, index) : null;
        } catch (Exception e) {
            return null;
        }
    }

    private static Project extractProject(String value, int index) {
        var identifier = value.substring(index + 1).trim();
        var name = value.substring(0, index).trim();
        return identifier.length() + name.length() > 0 ? new Project(identifier, name) : null;
    }
```

2024-05-31 18:32 UTC, brinxmat commented on src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
> +    void shouldScrapeProjectSeparatedBySlashAndColon() {
Might have created parameterized tests for expectations of Slash-y/Colon-y variants. Like `shouldCreateProjectWhenStringContainsSlash` etc.

2024-05-31 18:32 UTC, brinxmat commented on brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/Project.java
> +        try {
Does the try here do anything?

2024-06-03 08:38 UTC, anetteOlli approved these changes

2024-06-03 08:38 UTC, anetteOlli commented on brage-migration-common/src/main/java/no/sikt/nva/brage/migration/common/model/record/Project.java
> +        try {
Dette her er et av mange bevis på at Brage er en haug med matavfall i juni, samtidig som renovasjonsverket er i streik. 🤮

2024-06-03 08:38 UTC, anetteOlli commented on src/test/java/no/sikt/nva/scrapers/DublinCoreScraperTest.java
> +    @ValueSource(strings = {"EC/H2020/727610", "EC/H2020: 727610"})
Var det ikke en smartere måte å få ut navn på testene, slik at man får bedre navngivning i testene hvis de tryner?

2024-06-03 11:28 UTC, merged